const Texts = {
    centro: [
        "Beije uma parte do corpo de cada um da roda. Não vale repetir.",
        "Tirar a camiseta de alguém usando a boca",
        "Escolha alguém para decidir em quem você vai tomar um shot no umbigo (body shot)",
        "Com os olhos fechados, deverão encostar sua mão em alguém e você deverá adivinhar qual a parte do corpo",
        "Beije alguém da roda que tiver o aniversário mais próximmo do seu, as duas bebem",
        "Dê um beijo triplo, ou beba 3 vezes",
        "Beije uma pessoa que você nunca beijou na roda",
    ],
    direita: [
        "Lamber alguma parte do corpo da pessoa a sua esquerda, as duas bebem",
        "Beije a pessoa a sua esquerda.Os dois bebem.",
        "Beije a pessoa a sua esquerda em qualquer lugar...Menos nos lábios.",
        "A pessoa da sua esquerda fala em seu ouvido alguma sacanagem pra você falar para pessoa à direita",
        "Beije a barriga da pessoa a sua direita",
        "Escreva algo com a lingua na barriga da pessoa a sua esquerda, ela deve adivinhar ou beber",
        "Aperte de forma sensual o bumbum da pessoa a sua esquerda",
        "Beije o mamilo da pessoa a sua esquerda",
        "Você e a pessoa a sua esquerda devem ir ao banheiro e com as luzes apagadas, se abraçarem sem nenhuma roupa na parte superior do corpo",
        "Fique trancado com a terceira pessoa a sua esquerda no banheiro por uma rodada",
        "Beije a virilha da pessoa a sua esquerda",
        "Beije a pessoa a sua esquerda do pescoço até o umbigo",
        "A terceira pessoa a sua esquerda escolhe alguém da roda para você e ela desaparecerem por uma rodada",
    ],
    esqueda: [
        "Lamber alguma parte do corpo da pessoa a sua direita, as duas bebem",
        "Beije a pessoa a sua direita.Os dois bebem.",
        "Beije a pessoa a sua direita em qualquer lugar...Menos nos lábios.",
        "A pessoa da sua direita fala em seu ouvido alguma sacanagem pra você falar para pessoa à esquerda",
        "Beije a barriga da pessoa a sua direita",
        "Escreva algo com a lingua na barriga da pessoa a sua direita, ela deve adivinhar ou beber",
        "Aperte de forma sensual o bumbum da pessoa a sua direita",
        "Beije o mamilo da pessoa a sua direita",
        "Fique trancado com a terceira pessoa a sua direita no banheiro por uma rodada",
        "Beije a virilha da pessoa a sua direita",
        "Beije a pessoa a sua direita do pescoço até o umbigo",
        "A segunda pessoa a sua direita escolhe alguém da roda para você e ela desaparecerem por uma rodada",
    ],
    aquecimento: [
        "Bebe quem nunca ficou de ressaca.",
        "Todos que já participaram de um concurso bebem.",
        "O mestre bebe se ele / ela já caiu na rua.",
        "Bebe quem já desmaiou.",
        "Bebe quem já teve uma experiência paranormal.",
        "O mestre bebe se ele / ela já comeu alguma comida do lixo.",
        "Bebe quem já quebrou algo na casa de algum amigo e não disse.",
        "Bebe quem já colocou fogo no cabelo de outra pessoa.",
        "Bebe quem já disse acidentalmente 'Eu te amo' para alguém.",
        "Bebe quem já ficou preso no elevador.",
        "O mestre deve dizer qual foi o melhor momento da semana dele/a e escolher alguém para beber junto.",
        "Todos falam o que queriam ser quando crescer e todos bebem.",
        "A pessoa que menos dormiu na última noite deve beber.",
        "A pessoa que mais dormiu na última noite deve beber.",
        "Quem já levou um tapa na cara deve beber.",
        "Quem já deu um tapa na cara deve beber.",
        "Quem coloca ketchup na pizza deve beber.",
        "O mestre deve perguntar para todos da roda se um Oreo é biscoito ou bolacha. O mestre decide qual resposta é a correta. Quem falar a resposta errada deve beber.",
        "Quem já dançou no elevador deve beber.",
        "Quem já usou aparelho deve beber.",
        "Vegetarianos e veganos bebem.",
        "Quem já foi eletrocutado deve beber.",
        "A pessoa que demorou mais tempo para largar as fraldas deve beber.",
        "Quem já fez xixi na piscina deve beber.",
        "Bebe quem já saiu com alguém que conheceu em um aplicativo.",
        "Bebe quem nunca mentiu em uma carta dos Autobots.",
        "Conte a sua história em 30 segundos e depois beba.",
        "Bebe quem pratica algum tipo de esporte.",
        "Qual profissão você nunca teria? Ah! Você bebe.",
        "Qual é o seu filme favorito? Beba para cada hora de filme",
        "Qual é a sua série favorita? Quem gostar dela bebe também",
        "Qual é o seu livro favorito? Beba para cada palavra do título",
        "Qual é o seu gênero musical favorito? Beba",
        "Bebe quem já subiu em uma árvore.",
        "Quando foi a última vez que você mudou de ideia / opinião sobre alguma coisa? ",
        "Você é o último ser humano na Terra... qual seria a primeira coisa que você faria?",
        "Qual é a sua melhor característica? Ah! Você bebe.",
        "Qual é o seu vício? Escolha alguém para beber com você.",
        "Qual é o seu cheiro favorito? Ah! Você deve beber.",
        "Conte um fun fact sobre a sua vida e escolha alguém para beber logo em seguida.",
        "3 fatos sobre você. Beba 3 vezes.",
        "Todos deverão falar algo que acham interessante ou peculiar sobre você. Todo mundo bebe menos você.",
        "Qual é o seu maior orgulho?",
        "Qual foi a maior lição que você nunca aprendeu? Todo mundo bebe.",
        "Escolha alguém da roda, essa pessoa deverá contar um fun fact sobre ela. Ela bebe.",
        "Escolha alguém da roda e faça uma pergunta que você sempre quis fazer. Os dois bebem.",
        "Bebe quem gosta de cozinhar.",
        "Bebe quem tem medo do escuro.",
        "Quem da roda você levaria para uma ilha deserta? Justifique a sua resposta e os dois bebem.",
        "Se você tivesse que passar uma semana junto com alguém da roda preso em uma sala, quem você escolheria?",
        "Quem foi a sua primeira crush? Fale um verso e tome uma em sua homenagem",
        "Qual é o seu maior arrependimento? Beba pra aprender",
        "Qual nome você nunca daria para o seu filho/a?",
        "Conte a história de uma das suas cicatrizes.",
        "Qual é a a parte favorita do seu corpo? Beba",
        "Quais foram os seus crushes no último ano? Cite os nomes e beba",
        "Das pessoas nesta sala, com quem você mais gostaria de ficar? Beba",
        "Já ficou com alguém do Tinder? Beba",
        "Qual a maior mentira que já contou para algum namorado ou namorada e nunca foi descoberta? Beba",
        "Qual foi a coisa mais embaraçosa que seus pais já pegaram você fazendo? Beba",
        "Qual foi a coisa mais cruel que você já fez com um namorado ou namorada? Beba",
        "Qual foi a coisa mais estranha que você já fez em frente ao espelho? Beba",
        "Você já enviou alguma fotografia comprometedora para a pessoa errada? Beba",
        "Qual foi o lugar mais esquisito ou curioso em que ficou com alguém? Beba",
        "Qual o maior segredo que já escondeu de algum namorado ou namorada? Beba",
        "Quem foi a última pessoa com que ficou? Beba",
        "Já teve algum sonho sugestivo com alguém desta sala? Beba",
        "Qual seria a primeira coisa que você faria se acordasse por um dia sendo do gênero oposto? Beba",
        "Quando foi a última vez que te deram um fora e como lidou com isso? Beba",
        "O que você nunca toparia fazer pelo(a) namorado(a)? Beba",
        "Com quem quer muito ficar de novo? Beba",
        "Com quem gostaria de esquecer que ficou? Beba",
        "Já mandou a mesma fotografia para mais de uma pessoa? Beba",
        "Já ficou com algum professor? Beba",
        "Já viu algum vizinho trocando de roupa sem querer? Beba",
        "O que faria se pegasse seu namorado ou namorada com outro(a)? Beba",
        "Já ficou com o(a) ex-namorado(a) de um(a) amigo(a)? Beba",
        "Já sentiu ranço de alguém nesta sala? Beba",
        "Já foi apaixonado(a) por alguém nesta sala? Beba",
        "Já nadou sem roupa? Beba",
        "Já foi traído(a)? Beba",
        "O que te entrega quando está a fim de alguém? Beba",
        "Qual foi a maior mentira que contou para faltar o trabalho? Beba",
        "Já teve que esconder marcas deixadas no seu pescoço? Beba",
        "Tem alguma tatuagem escondida? Beba",
        "Tem algum piercing em um lugar que não podemos ver? Beba",
        "Em quem desta roda tem vontade de dar um beijo? Beba",
        "Qual foi o máximo de tempo que já ficou sem beijar alguém? Beba",
        "Já ficou com alguém sabendo que era comprometido(a)? Beba",
        "Já foi o(a) amante? Beba",
        "Já terminou um relacionamento porque se interessou por outra pessoa? Beba",
        "Em qual lugar do corpo gosta de receber massagem? Beba",
        "Qual é o tipo de provocação você não resiste? Beba",
        "Qual é a sua técnica de conquista que mais funciona? Beba",
        "Já ficou com pai ou mãe de amigo(a)? Beba",
        "Já ficou com primo(a)? Beba",
        "Eu nunca dancei em uma festa uma dança sexual com um desconhecido. Beba se já.",
        "Eu nunca beijei uma pessoa sem saber o nome dela. Beba se já.",
        "Eu nunca fiquei com mais de 2 pessoas na mesma noite. Beba se já.",
        "Eu nunca dei eu um beijo triplo. Beba se já.",
        "Eu nunca mandei nudes. Beba se já.",
        "Eu nunca fiquei com alguém da minha sala. Beba se já.",
        "Eu nunca fiquei com alguém do meu trabalho. Beba se já.",
        "Eu nunca flertei no transporte público. Beba se já.",
        "Eu nunca deixei meu telefone em um papel para um desconhecido. Beba se já.",
        "Eu nunca dancei em cima do palco de uma festa. Beba se já.",
        "Eu nunca fiz body shot. Beba se já.",
        "Eu nunca lambi algo que estava no corpo de alguém. Beba se já.",
        "EU nunca deixei passarem a mão em mim. Beba se já.",
        "Eu nunca cheguei em alguém na balada. Beba se já.",
        "Eu nunca seduzi alguém. Beba se já.",
        "Eu nunca rebolei para alguém. Beba se já.",
        "Eu nunca mandei memes safados no WhatsApp. Beba se já.",
        "EU nunca flertei no Direct do Insta. Beba se já.",
        "Eu nunca saí com alguém do Tinder ou outro app de paquera. Beba se já.",
        "Eu nunca fiquei com alguém de outro país. Beba se já.",
        "Eu nunca fiz coisas proibidas no cinema. Beba se já.",
        "Eu nunca joguei strip poker. Beba se já.",
        "Eu nunca assisti filme pornô. Beba se já.",
        "Eu nunca me apaixonei. Beba se já.",
        "Eu nunca fiz topless. Beba se já.",
        "Eu nunca nadei sem roupa. Beba se já.",
        "Eu nunca joguei verdade ou desafio só para dar selinho em alguém. Beba se já.",
        "Eu nunca fui à um motel. Beba se já.",
        "Eu nunca publiquei fotos sensuais. Beba se já.",
        "EU nunca gravei um vídeo sensual. Beba se já.",
        "Eu nunca fiquei com um famoso. Beba se já.",
        "Eu nunca saí sem calcinha ou cueca. Beba se já.",
        "Eu nunca fiquei com um vizinho. Beba se já.",
        "Eu nunca tive dúvidas quanto à minha sexualidade. Beba se já.",
        "Eu nunca disse 'eu te amo'. Beba se já.",
        "Eu nunca errei o nome de alguém que estava ficando. Beba se já.",
        "Eu nunca me declarei. Beba se já.",
        "Eu nunca usei aliança. Beba se já.",
        "Eu nunca usei uma lingerie sexual para surpreender alguém. Beba se já.",
        "Eu nunca fiz uma massagem sensual. Beba se já.",
        "Eu nunca recebi uma massagem sensual. Beba se já.",
        "Eu nunca fiquei com marca de mordida na boca. Beba se já.",
        "Eu nunca deixei marca de mordida em outra pessoa. Beba se já.",
        "Eu nunca fiquei com marcas de mordidas de outra pessoa pelo meu corpo. Beba se já.",
        "Eu nunca fiquei com duas pessoas ao mesmo tempo. Beba se já.",
        "Eu nunca sussurrei coisas safadas no ouvido de alguém. Beba se já.",
        "Eu nunca mandei as luas do WhatsApp para alguém 🌚🌝. Beba se já.",
        "Eu nunca li tutoriais de sexo na internet. Beba se já.",
        "Eu nunca fiquei com o ex de um amigo, beba se já",
        "Eu nunca usei camisinha. Beba se já.",
        "Eu nunca acordei com alguém do lado sem saber o nome da pessoa. Beba se já.",
        "Eu nunca fiz sexo casual. Beba se já.",
        "Eu nunca fiz sexo a 3. Beba se já.",
        "Eu nunca participei de uma suruba. Beba se já.",
        "Eu nunca fui algemado na cama. Beba se já.",
        "Eu nunca realizei uma fantasia sexual. Beba se já.",
        "Eu nunca fui a um motel. Beba se já.",
        "Eu nunca transei na cama dos meus pais. Beba se já.",
        "Eu nunca transei em um local público. Beba se já.",
        "Eu nunca fiz sexo anal. Beba se já.",
        "Eu nunca fiz sexo oral. Beba se já.",
        "Eu nunca recebi um beijo um grego. Beba se já.",
        "EU nunca dei um beijo grego. Beba se já.",
        "Eu nunca usei lubrificante. Beba se já.",
        "Eu nunca usei saliva ao invés de lubrificante. Beba se já.",
        "Eu nunca improvisei um lubrificante caseiro. Beba se já.",
        "Eu nunca usei um vibrador. Beba se já.",
        "Eu nunca usei outro objeto como se fosse um vibrador. Beba se já.",
        "Eu nunca usei gel sexual. Beba se já.",
        "Eu nunca vi/tive um squirt. Beba se já.",
        "EU nunca engoli. Beba se já.",
        "EU nunca recebi uma crítica construtiva durante o sexo. Beba se já.",
        "Eu nunca broxei. Beba se já.",
        "Eu nunca fingi um orgasmo. Beba se já.",
        "Eu nunca transei com a luz acesa/apagada. Beba se já.",
        "Eu nunca transei no mar. Beba se já.",
        "Eu nunca fiz sexo virtual. Beba se já.",
        "Eu nunca fiz sexo por telefone. Beba se já.",
        "Eu nunca encontrei o ponto G. Beba se já.",
        "Eu nunca transei na água. Beba se já.",
        "Eu nunca fui pego na hora H. Beba se já.",
        "Eu nunca me masturbei em um local proibido. Beba se já.",
        "Eu nunca fiz sexo no chuveiro. Beba se já.",
        "Eu nunca fiz uma atuação que fazia parte da fantasia sexual de alguém. Beba se já.",
        "Eu nunca tive um acidente sexual. Beba se já.",
        "Eu nunca usei produtos com sabor na hora de transar. Beba se já.",
        "Eu nunca transei em quarto que tinha espelho no teto. Beba se já.",
        "Eu nunca tive orgasmos múltiplos. Beba se já.",
        "Eu nunca fiz um 69. Beba se já.",
        "Eu nunca transei com os olhos vendados. Beba se já.",
        "Eu nunca fui a um sex shop. Beba se já.",
        "Eu nunca transei com alguém do mesmo sexo. Beba se já.",
        "Eu nunca tive uma DST. Beba se já.",
        "Eu nunca gozei sem penetração. Beba se já.",
        "Eu nunca usei chantily na cama. Beba se já.",
        "Eu nunca usei um plug anal. Beba se já.",
        "Eu nunca me masturbei na frente de outra pessoa. Beba se já.",
        "EU nunca fui a uma casa de swing. Beba se já.",
        "Eu nunca fiz troca de casais. Beba se já.",
        "Eu nunca tiver vergonha de pedir algo estranho na cama. Beba se já.",
    ],
    hot: [
        "Qual é a parte mais atraente da pessoa na sua frente?",
        "Beba um shot para cada pessoa da roda que você faria um oral. (Não diga o nome delas)",
        "Quem usa algum sex toy bebe.",
        "Apague a luz por uma rodada.",
        "Você faria um oral na pessoa a sua direita? Os dois bebem.",
        "Você faria um oral na pessoa a sua esquerda? Os dois bebem.",
        "Beije uma parte do corpo de cada um da roda. Não vale repetir.",
        "Faça a sua cara de orgasmo e beba.",
        "Abra um vídeo pornô e comece a narrar e comentar. Todo mundo bebe.",
        "Qual é o seu fetiche? Beba.",
        "Quem já participou de uma orgia bebe.",
        "Fique o mais perto da pessoa a sua esquerda que conseguir sem tocá-la até essa carta aparecer novamente.",
        "Fique o mais perto da pessoa a sua direita que conseguir sem tocá-la até essa carta aparecer novamente.",
        "O que você gosta de ver enquanto se masturba? Beba.",
        "Chupe um dedo da pessoa a sua esquerda.",
        "Chupe um dedo da pessoa a sua direita.",
        "Você já fingiu um orgasmo?",
        "Quem da roda você gostaria de ver sem roupa. As pessoas mencionadas bebem.",
        "Veja um pornô com a pessoa a sua direita.",
        "Veja um pornô com a pessoa a sua esquerda.",
        "Tire a calça por uma rodada.",
        "Você faria sexo por dinheiro? Beba de qualquer forma.",
        "Qual foi a sua pior experiência sexual? Beba.",
        "Com quem da roda você faria sexo essa noite? As pessoas mencionadas deverão beber.",
        "Coloque um cubo de gelo dentro da sua cueca ou calcinha.",
        "Faça uma lap dance na pessoa a sua frente.",
        "Todo mundo tira a camisa por uma rodada e todo mundo bebe.",
        "Refaça a sua posição sexual favorita com uma pessoa imaginária (e beba).",
        "Tire a camisa por uma rodada (e beba).",
        "Beije o pescoço da pessoa a sua esquerda, os dois bebem.",
        "Beije o pescoço da pessoa a sua direita, os dois bebem.",
        "Sente no colo da pessoa na sua frente por uma rodada.",
        "Quem já fez sexo em um local público bebe.",
        "Beije a pessoa a sua direita. Os dois bebem.",
        "Beije a pessoa a sua esquerda. Os dois bebem.",
        "Quem já beijou alguém do mesmo sexo bebe.",
        "Mostre um nude para a pessoa a sua esquerda... os dois bebem.",
        "Mostre um nude para a pessoa a sua direita... os dois bebem.",
        "Faça massagem na pessoa a sua esquerda (onde a pessoa a sua direita mandar).",
        "Faça massagem na pessoa a sua direita (onde a pessoa a sua esquerda mandar).",
        "Tire todas as suas peças de roupa. Você pode beber para cada peça não tirada.",
        "Passe uma rodada sentado(a) no colo da pessoa a sua esquerda.",
        "Passe uma rodada sentado(a) no colo da pessoa a sua direita.",
        "Finja um orgasmo olhando para a pessoa a sua esquerda. Os dois bebem.",
        "Finja um orgasmo olhando para a pessoa a sua direita. Os dois bebem.",
        "A pessoa que passou mais tempo sem sexo bebe.",
        "Quem é virgem bebe.",
        "Quem não é virgem bebe.",
        "Quem já fez um threesome bebe.",
        "Por uma rodada você só pode falar como se estivesse atingindo o orgasmo.",
        "Quem da roda você escolheria para um trizal? Os 3 bebem.",
        "A última pessoa que se masturbou bebe.",
        "Quem já beijou alguém do sexo diferente bebe.",
        "Beije a pessoa a sua esquerda em qualquer lugar... Menos nos lábios.",
        "Beba se você já teve um pensamento erótico com alguém da roda.",
        "A pessoa que perdeu a virgindade mais velho bebe.",
        "A pessoa que perdeu a virgindade mais novo bebe.",
        "Qual é a sua maior fantasia sexual? O mestre bebe.",
        "Faça uma lap dance na pessoa a esquerda.",
        "Faça uma lap dance na pessoa a direita.",
        "Beije a pessoa a sua direita em qualquer lugar... Menos nos lábios.",
        "Beba se estiver excitado(a).",
        "Fale uma sacanagem no ouvido da pessoa a sua direita",
        "Flerte com olhares com a pessoa a sua direita",
        "A pessoa da sua esquerda fala em seu ouvido alguma coisa pra você falar para pessoa à direita",
        "Fique por 1 rodadas em uma posição escolhida pelo grupo.",
        "Beije a barrida da pessoa a sua direita, ou beba",
        "Beije o pescoço da pessoa a sua direita",
        "Dê uma sarrada sensual na pessoa a sua direita",
        "Dê uma sarrada sensual na pessoa a sua esquerda",
        "Beije o pescoço da pessoa a sua direita",
        "Beije a barriga da pessoa a sua direita, ou beba",
        "Beije a barriga da pessoa a sua direita, ou beba",
        "A pessoa da sua direita fala em seu ouvido alguma coisa pra você falar para pessoa à esquerda",
        "Fale uma sacanagem no ouvido da pessoa a sua esquerda",
        "Flerte com olhares com a pessoa a sua esquerda",
        "Tirar a camiseta de alguém usando a boca",
        "Uma rodada fazendo cafuné em alguém da roda",
        "Tomar um shot no umbigo de alguém (body shot)",
        "Sussurre no ouvido da pessoa a sua direita as coisas que você costuma dizer na hora do sexo e beba",
        "Sussurre no ouvido da pessoa a sua esquerda as coisas que você costuma dizer na hora do sexo e beba",
        "Morder (de leve) o pescoço de alguém da roda, os dois bebem",
        "Com os olhos fechados, deverão encostar sua mão em alguém e você deverá adivinhar qual a parte do corpo",
        "Passar a próxima rodada no colo de alguém, as duas bebem",
        "Beije alguém da roda, as duas bebem",
        "Coloque um cubo de gelo na boca e dê um beijo no pescoço de alguém da roda, as duas bebem",
        "Lamber alguma parte do corpo de outra pessoa, as duas bebem",
        "Beba por cada pessoa da roda que você já beijou",
        "Lamba a orelha da pessoa a sua direita, os dois bebem",
        "Lamba a orelha da pessoa a sua esquerda, os dois bebem",
        "Escreva algo com a lingua na barriga da pessoa a sua esquerda, ela deve adivinhar ou beber",
        "Escreva algo com a lingua na barriga da pessoa a sua direita, ela deve adivinhar ou beber",
        "Dê uma palmada no bumbum da pessoa a sua direita",
        "Dê uma palmada no bumbum da pessoa a sua esquerda",
    ],
    autobots: [
        "Esconda um objeto pequeno dentro da roupa intima (parte de baixo) a pessoa a sua esquerda deve encontrar",
        "Esconda um objeto pequeno dentro da roupa intima (parte de baixo) a pessoa a sua direita deve encontrar ",
        "Todos devem fechar os olhos. Você pode beijar qualquer pessoa da roda. Os dois devem manter segredo. Os olhos só serão abertos quando você permitir",
        "Aperte de forma sensual o bumbum da pessoa a sua direita",
        "Aperte de forma sensual o bumbum da pessoa a sua esquerda",
        "Escolha duas pessoas, elas deverão se beijar (os 3 bebem).",
        "Coloque a sua mão dentro da calça da pessoa a sua esquerda por uma rodada ou os dois bebem.",
        "Coloque a sua mão dentro da calça da pessoa a sua direita por uma rodada ou os dois bebem.",
        "A roda decide quem o mestre deve beijar.",
        "Beije a pessoa que você acha mais atraente na roda.",
        "Dê um beijo triplo, ou beba 3 vezes",
        "Vá até o banheiro com a pessoa a sua direita e dê um beijo em qualquer parte do corpo",
        "Vá até o banheiro com a pessoa a sua esquerda e dê um beijo em qualquer parte do corpo",
        "Escolha duas pessoas para se beijarem, as duas devem beber",
        "Beije o mamilo da pessoa a sua direita",
        "Beije o mamilo da pessoa a sua esquerda",
        "Você e a pessoa a sua esquerda devem ir ao banheiro e com as luzes apagadas, se abraçarem sem nenhuma roupa na parte superior do corpo",
        "Você e a pessoa a sua direta devem ir ao banheiro e com as luzes apagadas, se abraçarem sem nenhuma roupa na parte superior do corpo",
        "A roda decide em você dará um chupão (é permitido deixar marca)",
        "Você deverá apalpar de maneira sensual alguma parte do corpo da pessoa a sua direita",
        "Você deverá apalpar de maneira sensual alguma parte do corpo da pessoa a sua esquerda",
        "Fique trancado com a terceira pessoa a sua direita no banheiro por uma rodada",
        "Fique trancado com a terceira pessoa a sua esquerda no banheiro por uma rodada",
        "Deite-se. A pessoa a sua direita deverá ficar por cima. simulem sexo por 10 segundos nessa posição",
        "Deite-se. A pessoa a sua esquerda deverá ficar por cima. simulem sexo por 10 segundos nessa posição",
        "Sussurre no ouvido da pessoa a sua direita qual o seu ponto forte na cama",
        "Sussurre no ouvido da pessoa a sua esquerda qual o seu ponto forte na cama",
        "Beije um autobot da diretoria",
        "Feche os olhos, alguém da roda te dá um beijo, você precisa adivinhar quem é ou bebe",
        "Estimule duas partes do corpo da pessoa a sua esquerda. Uma usando as mãos e a outra com os lábios.",
        "Estimule duas partes do corpo da pessoa a sua direita. Uma usando as mãos e a outra com os lábios.",
        "Fique sem cueca/calcinha e beba",
        "Faça o que quiser com a pessoa a sua direita",
        "Faça o que quiser com a pessoa a sua esquerda",
        "Beije a virilha da pessoa a sua direita",
        "Beije a virilha da pessoa a sua esquerda",
        "Beije a pessoa a sua esquerda do pescoço até o umbigo",
        "Beije a pessoa a sua direita do pescoço até o umbigo",
        "Faça uma massagem na pessoa a sua direita dos pés até a virilha",
        "Faça uma massagem na pessoa a sua esquerda dos pés até a virilha",
        "Massageie as nádegas da pessoa a sua direita",
        "Massageie as nádegas da pessoa a sua esquerda",
        "Faça um strip tease para a pessoa a sua esquerda",
        "Faça um strip tease para a pessoa a sua direita",
        "Tire uma peça de roupa da pessoa a sua esquerda",
        "Tire uma peça de roupa da pessoa a sua direita",
        "A pessoa a sua esquerda escolhe alguém da roda para você e ela desaparecerem por uma rodada",
        "A pessoa a sua direita escolhe alguém da roda para você e ela desaparecerem por uma rodada",
        "Apalpe os peitos/seios da pessoa sua direita",
        "Apalpe os peitos/seios da pessoa sua esquerda",
        "Morda o bumbum da pessoa a sua direita",
        "Morda o bumbum da pessoa a sua esquerda",
        "A roda escolhe o que você deverá fazer. A ideia mais votada vence",
        "Beije uma pessoa que você ja beijou na roda",
        "Beije uma pessoa que você nunca beijou na roda",
        "Abra o ziper da pessoa a sua direita seensualmente, sem perder o contato visual, os dois bebem",
        "Abra o ziper da pessoa a sua esquerda seensualmente, sem perder o contato visual, os dois bebem",
    ]
}

export default Texts;