const Texts = {
    direita: [
        'pra_direita - a',
        'pra_direita - b',
        'pra_direita - c',
        'pra_direita - d',
    ],
    esqueda: [
        'pra_esqueda - a',
        'pra_esqueda - b',
        'pra_esqueda - c',
        'pra_esqueda - d',
    ],
    aquecimento: [
        'nivel1 - a',
        'nivel1 - b',
        'nivel1 - c',
        'nivel1 - d',
    ],
    hot: [
        'nivel2 - a',
        'nivel2 - b',
        'nivel2 - c',
        'nivel2 - d',
    ],
    autobots: [
        "Esconda um objeto pequeno dentro da roupa intima (parte de baixo) a pessoa a sua esquerda deve encontrar",
        "Esconda um objeto pequeno dentro da roupa intima (parte de baixo) a pessoa a sua direita deve encontrar",
        "Todos devem fechar os olhos. Você pode beijar qualquer pessoa da roda. Os dois devem manter segredo. Os olhos só serão abertos quando você permitir",
        "Aperte de forma sensual o bumbum da pessoa a sua direita",
        "Aperte de forma sensual o bumbum da pessoa a sua esquerda",
        "Escolha duas pessoas, elas deverão se beijar (os 3 bebem).",
        "Coloque a sua mão dentro da calça da pessoa a sua esquerda por uma rodada ou os dois bebem.",
        "Coloque a sua mão dentro da calça da pessoa a sua direita por uma rodada ou os dois bebem.",
        "A roda decide quem o mestre deve beijar.",
        "Beije a pessoa que você acha mais atraente na roda.",
        "Dê um beijo triplo, ou beba 3 vezes",
        "Vá até o banheiro com a pessoa a sua direita e dê um beijo em qualquer parte do corpo",
        "Vá até o banheiro com a pessoa a sua esquerda e dê um beijo em qualquer parte do corpo",
        "Escolha duas pessoas para se beijarem, as duas devem beber",
        "Beije o mamilo da pessoa a sua direita",
        "Beije o mamilo da pessoa a sua esquerda",
        "Você e a pessoa a sua esquerda devem ir ao banheiro e com as luzes apagadas, se abraçarem sem nenhuma roupa na parte superior do corpo",
        "Você e a pessoa a sua direta devem ir ao banheiro e com as luzes apagadas, se abraçarem sem nenhuma roupa na parte superior do corpo",
        "A roda decide em você dará um chupão (é permitido deixar marca)",
        "Você deverá apalpar de maneira sensual alguma parte do corpo da pessoa a sua direita",
        "Você deverá apalpar de maneira sensual alguma parte do corpo da pessoa a sua esquerda",
        "Dê uma palmada no bumbum da pessoa a sua direita",
        "Dê uma palmada no bumbum da pessoa a sua esquerda",
        "Deite-se. A pessoa a sua direita deverá ficar por cima. simulem sexo por 10 segundos nessa posição",
        "Deite-se. A pessoa a sua esquerda deverá ficar por cima. simulem sexo por 10 segundos nessa posição",
        "Sussurre no ouvido da pessoa a sua direita qual o seu ponto forte na cama",
        "Sussurre no ouvido da pessoa a sua esquerda qual o seu ponto forte na cama",
    ]
}

export default Texts;